// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Credentials struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

type NewUser struct {
	FirstName       string `json:"firstName"`
	LastName        string `json:"lastName"`
	Username        string `json:"username"`
	Password        string `json:"password"`
	PasswordConfirm string `json:"passwordConfirm"`
	Email           string `json:"email"`
	AccountID       int    `json:"accountId"`
	PrimaryTeamID   int    `json:"primaryTeamId"`
	RoleID          int    `json:"roleId"`
}

type PasswordChange struct {
	OldPassword        string `json:"oldPassword"`
	NewPassword        string `json:"newPassword"`
	NewPasswordConfirm string `json:"newPasswordConfirm"`
}

type Role struct {
	ID          string `json:"id"`
	AccessLevel int    `json:"accessLevel"`
	Name        string `json:"name"`
}

type UpdateUser struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Address   string `json:"address"`
	Mobile    string `json:"mobile"`
	Phone     string `json:"phone"`
}

type User struct {
	FirstName          string `json:"firstName"`
	LastName           string `json:"lastName"`
	Username           string `json:"username"`
	Password           string `json:"password"`
	PasswordConfirm    string `json:"passwordConfirm"`
	Email              string `json:"email"`
	Mobile             string `json:"mobile"`
	Phone              string `json:"phone"`
	Address            string `json:"address"`
	AccountID          int    `json:"accountId"`
	PrimaryTeamID      int    `json:"primaryTeamId"`
	Role               Role   `json:"role"`
	UpdatedAt          string `json:"updatedAt"`
	CreatedAt          string `json:"createdAt"`
	DeletedAt          string `json:"deletedAt"`
	LastPasswordChange string `json:"lastPasswordChange"`
	LastLogin          string `json:"lastLogin"`
}
