# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

      - image: mysql:latest
        command: mysqld --sql_mode=""
        restart: always
        ports:
          - 3306:3306
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: cerebrum_mysql_test_db
          MYSQL_USER: mysql_test_user
          MYSQL_PASSWORD: mysql_test_password
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/johncoleman83/cerebrum
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: install dependencies
          command: go get -t -v ./...

      - run:
          name: test all
          command: ./test

      - run:
          name: ensure golint is installed
          command: go get -u golang.org/x/lint/golint

      - run:
          name: run lint
          command: make lint

      # token required for private projects 'bash <(curl -s https://codecov.io/bash) -t token'
      - run:
          name: codecov.io
          command: bash <(curl -s https://codecov.io/bash)
