database:
  dialect: mysql
  user: mysql_test_user
  password: mysql_test_password
  name: cerebrum_mysql_test_db
  protocol: tcp
  host: localhost
  port: 3306
  settings: tls=skip-verify&charset=utf8&parseTime=True&loc=Local&autocommit=true&timeout=20s

server:
  port: :8080
  debug: true
  read_timeout_seconds: 15
  write_timeout_seconds: 20

jwt:
  secret: dsflaksdhflaksdhfalksjdhflasdfh
  duration_minutes: 10
  refresh_duration_minutes: 10
  max_refresh_minutes: 144
  signing_algorithm: HS384

application:
  min_password_strength: 3
  swagger_ui_path: third_party/swaggerui/dist
